[build]
  command = "npm run build"
  publish = "out"
  functions = ".netlify/functions"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  exclude = [
    './404/index.html',
    './not-found/index.html',
    './cases/**/index.html'
  ]